sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t btilki/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true btilki/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-588757570737"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $acceskey
  secret_access_key: $secretkey
